# Generated by Django 5.2.1 on 2025-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Изображение будет показано в круглом формате над содержимым', null=True, upload_to='covers/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
